<div class="jumbotron">
    <h2>Manage Products</h2>
</div>

<div class="row col-md-6 col-md-offset-2 custyle">
   <a href="<?php echo $this->url('product-list') ?>" class="btn btn-primary"><b>+</b> All Products</a>
   <br>
   <form role="form">
        <h3 >Add new Product</h3>
          <div class="alert hidden"></div>
          <div class="form-group">
            <select class="form-control" id='category' name="category">
                <option>Select category</option>
                <?php foreach ($categories as $row): ?>
                  <option value="<?php echo $row->id; ?>"><?php echo $row->name; ?></option>
                <?php endforeach; ?>
            </select>
          </div>
          <div class="form-group">
						<input type="text" class="form-control" id='title' name="title" placeholder="Product Name" required>
					</div>
          <div class="form-group">
						<input type="text" class="form-control" id='price' name="price" placeholder="Price" required>
					</div>
          <div class="form-group">
						<textarea class="form-control" id='description' name="description" placeholder="Description" rows="5"></textarea>
					</div>
        <button type="button" id="submit" name="submit" class="btn btn-success pull-right">Add</button>
        <br/>
        <br/>
        <br/>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#submit').click(submit);

    function submit(){
      $.post( "<?php echo $this->url('product-add-ajax') ?>",
            {
              title:$('#title').val(),
              description:$('#description').val(),
              price:$('#price').val() ,
              category:$('#category').val()
            } ,
      function( data ) {
         var response = '<i class="glyphicon glyphicon-check"></i> Data Saved, Thanks! ';
         $('.alert').html(response).removeClass('hidden').addClass('alert-success');
      });
    }
  });
</script>
