<div class="jumbotron">
    <h1>Manage Products</h1>
</div>

<div class="row col-md-6 col-md-offset-2 custyle">
  <a href="#" class="btn btn-primary"><b>+</b> Add new Product</a>
  <br><br>
   <table class="table table-striped">
   <thead>
       <tr>
           <th>ID</th>
           <th>Product name</th>
           <th>description</th>
           <th>created date</th>
           <th>category</th>
           <th class="text-center">Action</th>
       </tr>
   </thead>
           <tr>
               <td>1</td>
               <td>News</td>
               <td>News</td>
               <td>News</td>
               <td class="text-center">
                 <a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                 <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
               </td>
           </tr>
           <tr>
               <td>2</td>
               <td>Products</td>
               <td>Products</td>
               <td>Products</td>
               <td class="text-center">
                 <a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                 <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
               </td>
           </tr>
           <tr>
               <td>3</td>
               <td>Blogs</td>
               <td>Blogs</td>
               <td>Blogs</td>
               <td class="text-center">
                 <a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                 <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
               </td>
           </tr>
   </table>
   </div>
