<div class="jumbotron">
    <h1>Manage Categories</h1>
</div>

<div class="row col-md-6 col-md-offset-2 custyle">
   <a href="<?php echo $this->url('category-list') ?>" class="btn btn-primary"><b>+</b> All Categories</a>
   <br><br>
   <form role="form">
        <h3 >Add new Category</h3>
          <div class="alert hidden"></div>
    			<div class="form-group">
						<input type="text" class="form-control" id='name' name="name" placeholder="Name" required>
					</div>
        <button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Add</button>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#submit').click(submit);

    function submit(){
      $.post( "<?php echo $this->url('category-add-ajax') ?>",{name:$('#name').val()} ,function( data ) {
         var response = '<i class="glyphicon glyphicon-check"></i> Data Saved, Thanks! ';
         $('.alert').html(response).removeClass('hidden').addClass('alert-success');
         $('#name').val('');
      });
    }
  });
</script>
