<div class="jumbotron">
    <h1>Manage Categories</h1>
</div>

<div class="row col-md-10 col-md-offset-2 custyle">
  <a href="<?php echo $this->url('category-add') ?>" class="btn btn-primary"><b>+</b> Add new Category</a>
  <br><br>
   <table class="table table-striped">
     <?php
      // echo "<pre>";
      // var_dump($categories);
      // echo "</pre>";

     ?>
   <thead>
       <tr>
           <th>ID</th>
           <th>Category name</th>
           <th class="text-center">Action</th>
       </tr>
   </thead>
      <?php foreach ($categories as $cat) { ?>
           <tr>
               <td><?php echo $cat->id ?></td>
               <td><?php echo $cat->name ?></td>
               <td class="text-center">
                 <a class='btn btn-default btn-xs' href="javascript:alert('in progress...')"><span class="glyphicon glyphicon-eye-open"></span> View Products </a>
                 <a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                 <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
               </td>
           </tr>
      <?php } ?>
   </table>
   </div>
