<h1>Products <a href="<?= $this->url('product').DIRECTORY_SEPARATOR .  'add' ?>" class="btn btn-primary btn-lg pull-right">Add</a>
    <table class="table">
        <thead>
        <tr>
            <th>Title</th>
            <th>Created Time</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->products as $product): ?>
            <tr>
                <td> <?= $this->escapeHtml($product->getTitle()); ?></td>
                <td> <?= $this->escapeHtml($product->getDateCreated()); ?></td>
                <td>
                    <a href="<?= $this->url('product').DIRECTORY_SEPARATOR .  'edit' ?>" class="btn btn-success btn-lg pull-right">Edit</a>
                    <a href="<?= $this->url('product').DIRECTORY_SEPARATOR .  'delete' ?>" class="btn btn-danger btn-lg pull-right">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>



