<?php
$form = $this->form;
$form->get('title')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter product title here'
]);


$form->get('category_id')->setAttributes([
    'class' => 'form-control',
]);


$form->get('price')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Product</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>


        <div class="form-group">
            <?= $this->formLabel($form->get('category_id')); ?>
            <?= $this->formElement($form->get('category_id')); ?>
            <?= $this->formElementErrors($form->get('category_id')); ?>
        </div>


        <div class="form-group">
            <?= $this->formLabel($form->get('price')); ?>
            <?= $this->formElement($form->get('price')); ?>
            <?= $this->formElementErrors($form->get('price')); ?>
        </div>


        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   