<div class="jumbotron">
    <h1>Edit Category</h1>
</div>
<div>
    <form class="form-horizontal" action="/categories/edit/<?php echo $category->getId(); ?>" method="post">
        <div class="form-group">
            <label for="name">Name: </label>
            <input class="form-control" type="text" name="name" value="<?php echo $category->getName(); ?>" id="name" placeholder="name">
        </div>

        <div class="form-group">
            <label for="description">Description: </label>
            <input class="form-control" type="text" name="description" value="<?php echo $category->getDescription(); ?>" id="description" placeholder="description">
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit">
        </div>
    </form>
</div>
