<div class="jumbotron">
    <h1 class="text-center">Create New Category</h1>
</div>
<div>
    <form class="form-horizontal" action="/categories/new" method="post">
        <div class="form-group">
            <label for="name">Name: </label>
            <input class="form-control" type="text" name="name" id="name" placeholder="name">
        </div>

        <div class="form-group">
            <label for="description">Description: </label>
            <input class="form-control" type="text" name="description" id="description" placeholder="description">
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit">
        </div>
    </form>
</div>
