<h1>Categories <a href="<?= $this->url('category').DIRECTORY_SEPARATOR .  'add' ?>" class="btn btn-primary btn-lg pull-right">Add</a>
 </h1>


<table class="table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Created Time</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->categories as $category): ?>
        <tr>
            <td> <?= $this->escapeHtml($category->getTitle()); ?></td>
            <td> <?= $this->escapeHtml($category->getDateCreated()); ?></td>

            <td>
                <a href="<?= $this->url('category').DIRECTORY_SEPARATOR .  'edit' ?>" class="btn btn-success btn-lg pull-right">Edit</a>
                <a href="<?= $this->url('category').DIRECTORY_SEPARATOR .  'delete' ?>" class="btn btn-danger btn-lg pull-right">Delete</a>
            </td>

        </tr>
    <?php endforeach; ?>

    </tbody>
</table>



