<div class="jumbotron">
    <h1>Products</h1>
</div>
<div>
    <a href="/products/new" class="btn btn-success">Create New Product</a>
</div>
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($products as $product)
            {
                echo "<tr>";
                    echo "<td>".$product->getName()."</td>";
                    echo "<td>".$product->getDescription()."</td>";
                    echo "<td><a href='/products/show/".$product->getId().
                        "'> show <i class='glyphicon glyphicon-play'></i></a>";
                    echo "<a href='/products/edit/".$product->getId().
                        "'> edit <i class='glyphicon glyphicon-edit'></i></a>";
                    echo "<a href='/products/delete/".$product->getId().
                        "'> delete <i class='glyphicon glyphicon-remove'></i></a>".
                        "</td>";
                echo "</tr>";
            }
            ?>
        </tbody>
    </table>
</div>