<div class="jumbotron">
    <h1 class="text-center"><?php echo $product->getName(); ?></h1>
</div>
<div class="container">
    <pre>Price: <?php echo $product->getPrice(); ?></pre>
    <pre>Category: <a href='/categories/show/<?php echo $product->getCategory()->getId();?>'><?php echo $product->getCategory()->getName();?></a></pre>
    <pre>Description: <?php echo $product->getDescription(); ?></pre>
    <a href='/products/edit/<?php echo $product->getId() ?>' class="btn btn-success">Edit this Product</a>
</div>
